name: usgs-streamflow
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy<2
  - pandas<2.3
  - matplotlib
  - shapely
  - geopandas
  - folium
  - dataretrieval
  - pyarrow
  - bottleneck
  - numexpr
